[package]
name = "rounde-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/bin/server/main.rs"

[dependencies]
snafu = "0.8.6"

[dependencies.uuid]
version = "1.17.0"
features = [
    "v4",
]
