[package]
name = "rounde-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
socket2 = "0.5.10"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"